config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  
  resources :users do
    get '1830'
    get 'check_on_server', to: 'users#check_on_server', as: :check_on_server

    resources :nes do#, only: [:new, :create, :destroy]
      post 'upgrade'
      get 'delete'
      get 'ping_result'
      get 'version_result'
    end

    resources :branches do
      get 'delete'
      get 'update'
      get 'update_result'
    end
  end

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  belongs_to :user

  	validates :name, presence: true, :uniqueness => true
  	validates :root, presence: true
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_user
  before_action :set_branch  #, only: [:show, :edit, :update, :destroy]

  # GET /branches
  # GET /branches.json
  def index
    #@branches = @user.branches.all
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
    #@branch = @user.branches.find(params[:branch_id])
  end

  # GET /branches/new
  def new
    @branch = @user.branches.new
  end

  # GET /branches/1/edit
  def edit
    #@branch = @user.branches.find(params[:branch_id])
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = @user.branches.new(branch_params)
    @branch.save
    respond_to do |format|
      format.js {flash[:notice] = "Branch was created"}
    end
  end

  # PATCH/PUT /branches/1
  # PATCH/PUT /branches/1.json
  def update
    respond_to do |format|
      format.js {flash[:notice] = "Branch was updated"}
    end
    @branch.update_attributes(branch_params)
  end

  def delete
    #@branch = @user.branches.find(params[:branch_id])
  end
  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Branch item was successfully deleted.' }
    end
  end

  private
    def set_user
      @user = User.first
    end
    # Use callbacks to share common setup or constraints between actions.
    #def set_branch
    #  @branch = Branch.find(params[:id])
    #end
        # Use callbacks to share common setup or constraints between actions.
    def set_branch
      if params.include? :branch_id
        @branch = @user.branches.find(params[:branch_id])
      end
      if params.include? :id
        @branch = @user.branches.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def branch_params
      params.require(:branch).permit(:name, :completed, :root, :http, :user_id)
    end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete Branch</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you wish to delete <b><%= @branch.name %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to "Confirm", user_branch_path(@user, @branch), method: :delete, class: "btn btn-primary" %>
    <%= link_to "Cancel", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/branches/_edit.html.erb
<div class="modal-dialog">
  <div class="modal-content">
	<div class="modal-header">
	  <h3><%= "Editing #{@branch.name}" %></h3>
	</div>
	<%= render "form" %>
  </div>
</div>

app/views/branches/_form.html.erb
<%= form_for [@user, @branch], remote: true, html: { style: "display:inline;" } do |f| %>

  <div class="modal-body">
    <ul class="errors"></ul>

    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">>
      <%= f.label "release complete?" %><br>
      <%= f.check_box :completed %>
    </div>
    <div class="form-group">
      <%= f.label :root %><br>
      <%= f.text_field :root %>
    </div>
    <div class="form-group">
      <%= f.label :http %><br>
      <%= f.text_field :http %>
    </div>

  </div>

  <div class="modal-footer">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
  </div>
<% end %>

app/views/branches/_new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
	<div class="modal-header">
	<h3>New Branch</h3>
	</div>
	<%= render "form" %>
  </div>
</div>

app/views/branches/_save.js.erb
$("ul.errors").html("")
<% if @branch.errors.any? %>
  <% @branch.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  location.reload();
<% end %>

app/views/branches/delete.js.erb
<!-- window.alert("hey") -->
$("#branch-modal").html("<%= j render 'delete' %>")
$("#branch-modal").modal("show")

app/views/branches/edit.js.erb
$("#branch-modal").html("<%= j render 'edit' %>")
$("#branch-modal").modal("show")

app/views/branches/new.js.erb
$("#branch-modal").html("<%= j render 'new' %>")
$("#branch-modal").modal("show")