config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  
  resources :users do
    get '1830'
    get 'check_on_server', to: 'users#check_on_server', as: :check_on_server

    resources :nes do#, only: [:new, :create, :destroy]
      post 'upgrade'
      get 'delete'
      get 'ping_result'
      get 'version_result'
    end

    resources :branches do
      get 'delete'
      get 'update'
      get 'update_result'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :nes, dependent: :destroy
	has_many :branches, dependent: :destroy

  	def ectypes
  		return ['EC', 'ECX', 'ARMADA', 'PSS4', 'ECE']
  	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  helper_method :add_job
	# =================================================================
  def index
	# =================================================================
    #@site = 'http://pssnfs-lx.mh.lucent.com/1830wiki/1830PSS_Fruits_G_Deliveries'
    @nes = @user.nes
		@branches = @user.branches
    #Q1. do I need to reping NEs?
    #Q2. do I need to refresh the load?
    initialize_stack()
    if not db_up_to_date?
      for ne in @nes
        params = {user: @user,  ne: ne }
        ne.update_attributes({job_status: Ne::JOB_STATUS[:start] })
        add_job('ping', params)
        #add_job('version', params)
      end
    else
      # if previous session ended badly > overwrite :job_status
      for ne in @nes
        if ne[:job_status] != Ne::JOB_STATUS[:done]
          #ne.update_attributes({job_status: Ne::JOB_STATUS[:done] })
          params = {user: @user,  ne: ne }
          add_job('ping', params)
        end
      end
    end

  end
  #for branch in @branches
  #  site = 'http://localhost:3000/users/9/1830'
  #  looking_for = "grape-"
  #  BranchUpdateJob.perform_async(@user, branch, site, looking_for)
  #end
  #Q3. Do I need to reload  release latest load?
  def job_performing?
    for ne in @nes
      if ne[:job_status] == Ne::JOB_STATUS[:start]
        return true
      end
    end
    return false
  end

  def db_up_to_date?
    for ne in @nes
      time =  (Time.now - ne[:updated_at]).seconds / 60 # minutes
      #Did enough time pass?
      if time > 10
        return false
      end
    end
    return true
  end

  def add_job(job, params)
    #params = {user: @user,  ne: ne, job: PingerJob.perform_async }
    #First let's show user the page. then we'll come back to the stack
    @@stack.push([job, params])
  end

  # many jobs here.
  def check_on_server()
    #puts 'check_on_server()'
    #job_status = Job.first['status']
    #refresh
    @nes = @user.nes
    job_performing= job_performing?

    if not job_performing and db_up_to_date?
      render json: nil, status: :ok
      #respond_to do |format|
      #    format.html { redirect_to root_path }
      #end
    else
      if @@stack.length() > 0
        check_on_stack()
        #service_unavailable
        render json: nil, status: :service_unavailable
      else
        render json: nil, status: :service_unavailable
      end
    end
  end

  def check_on_stack()
    #Job.first.update_attributes(status: "busy")
    #status = Job.first[:status]
    #if status == 'done'
    for pair in @@stack
      params = pair[1]
      job = pair[0]
      case
      when job == 'ping'
        PingerJob.perform_async(params)
        #PingerJob.perform_in(@timein, params)
      when job == 'version'
        VersionJob.perform_async(params)
        #VersionJob.perform_in(@timein, params)
    end
    end
    initialize_stack()
    #Job.first.update_attributes(status: "done")
  end


  def initialize_stack()
    @@stack = []
  end




















  # GET /user/edit
  def edit
  end
  # PATCH/PUT /user/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_path, notice: 'User Profile was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end  
	# =================================================================
	def getVersion (system)
	# =================================================================
		@dir = '/home/astariko/APT/aptDev/testcase/ot/encryption/KMT/'
		@command = 'cd ' +@dir + '; python ne_handshake.py --system ' 
							+system + ' --config ne_handshake.cfg'
		# sort of run checks in background whether it was finished... << That is interesting.
		# OR! run tests on all systems at once.  Each one can write to system_name.txt
	end

	# =================================================================
	def isOnline (ip)
	# =================================================================
		cmd = 'ping -c 1 ' + ip	
		result = `#{cmd}`
		words = result.split(' ')
		words.each do |word|
			#packet loss is ....
			return false if word == '100%'
			return true if word == '0%'
		end
		return false
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.first
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:rootec, :rootecx, :rootece, :rootarmada, :rootpss4)
    end
end

app/views/users/_form.html.erb
<%= form_for([@user]) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this Profile from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rootec %><br>
    <%= f.text_field :rootec %>
  </div>
  <div class="field">
    <%= f.label :rootecx %><br>
    <%= f.text_field :rootecx %>
  </div>
  <div class="field">
    <%= f.label :rootece %><br>
    <%= f.text_field :rootece %>
  </div>
  <div class="field">
    <%= f.label :rootarmada %><br>
    <%= f.text_field :rootarmada %>
  </div>
  <div class="field">
    <%= f.label :rootpss4 %><br>
    <%= f.text_field :rootpss4 %>
  </div>
  <br>

  <div class="actions">
    <input class="btn btn-primary btn-block" type="submit" value="Submit" />
  </div>
  <br>
<% end %>

app/views/users/_index.html.erb
<p id="notice"><%= notice %></p>
<span id="check-on-server" data-path="<%= user_check_on_server_path(@user)%>" ></span>

<div id= "ne-list" class="subcontainer col-lg-10 col-md-10">
  <!--                          NE list                              -->
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>
          <input id= "ne-check-all" type="checkbox" />
        </th>
        <th>Name</th>
        <th>Status</th>
        <th>Load</th>
        <th>System</th>
        <th>ECType</th>
      </tr>
    </thead>

    <tbody class="ne-index">
    <% for ne in @nes %>
    <tr>
      <td>
        <span> <input class="ne-check" type="checkbox" value=<%= ne[:id] %> > </span>
      </td>
      <td> <%= ne[:name] %> </td>
      <td> 
        <div class="ne-status" id="ne-status-<%=ne[:id]%>" data-path="<%= user_ne_ping_result_path(@user, ne)%>">In-progress</div>
      </td>
      <td> <%= ne[:version] %> </td>
      <td> <%= ne[:system] %> </td>
      <td> <%= ne[:ectype] %> 
      
        <!-- These buttons lay within ECTYPE cell not to create their own -->
        <%= button_to "delete", user_ne_delete_path(@user, ne), remote: true, :method => :get, 
          :form => {"style" => "display:none", "id" => "delete-"+ne[:id].to_s}, :data => ne[:id] %>

        <%= button_to "edit", edit_user_ne_path(@user, ne), :remote => true, :method => :get, 
          :form => {"style" => "display:none", "id" => "edit-"+ne[:id].to_s}, :data => ne[:id] %>

        <%= button_to "upgrade", user_ne_upgrade_path(@user, ne), :method => :post, 
          :form => {"style" => "display:none", "id" => "upgrade-"+ne[:id].to_s}, :data => ne[:id] %>
      </td>
    </tr>

    <% end %>
    </tbody> 
  </table>

  <div id="ne-modal" class="modal fade"></div>
</div> <!-- NE list -->


<!-- Attempt to load Branches dynamically -->
<div id= "profile-list" class="subcontainer col-lg-10 col-md-10">

  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>
          <input id= "branch-check-all" type="checkbox" />
        </th>
        <th>Name</th>
        <th>Released?</th>
        <th>Latest Load</th>
        <th>Root</th>
        <!-- <td>&nbsp;</td> -->
      </tr>
    </thead>

    <tbody class="branch-index">
      <% @branches.each do |branch| %>
        <tr>
          <td>
          <span> <input class="branch-check" type="checkbox" value=<%= branch[:id] %> > </span>
          </td>
          <td><%= branch.name %></td>
          <td><%= branch.completed %></td>
          <td><div class="branch-latest-load" data-path="<%= user_branch_update_path(@user, branch)%>">in-progress</div></td>
          <td><%= branch.root %>
            <!-- These buttons lay within ECTYPE cell not to create their own -->
            <%= button_to "delete", user_branch_delete_path(@user, branch), remote: true, :method => :get, 
              :form => {"style" => "display:none", "id" => "delete-"+branch[:id].to_s}, :data => branch[:id] %>

            <%= button_to "edit", edit_user_branch_path(@user, branch), :remote => true, :method => :get, 
              :form => {"style" => "display:none", "id" => "edit-"+branch[:id].to_s}, :data => branch[:id] %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div id="branch-modal" class="modal fade"></div>
</div> <!-- Profile list -->

app/views/users/edit.html.erb
<div id="main-content" class="container">
  <%= render "/leftpane" %>

    <div id= "load-list" class="subcontainer col-lg-10 col-md-10">
      <div class="col-lg-2 col-md-2 col-sm-2">
          <%= render 'form' %>
      </div>
    </div> <!-- load-list -->

</div>

app/views/users/index.html.erb
<div id="main-content" class="container">
  <%= render "/leftpane" %>
  <%= render "index" %>
</div>

app/views/users/show.html.erb
<div id="main-content" class="container">
  <%= render "/leftpane" %>

  	<p id="notice"><%= notice %></p>
    <div id= "load-list" class="subcontainer col-lg-10 col-md-10">
      <div class="col-lg-6 col-md-6 col-sm-6">

		<p>
		  <strong>NE name:</strong>
		  <%= @ne.name %>
		</p>

		<p>
		  <strong>IP:</strong>
		  <%= @ne.ip %>
		</p>

		<p>
		  <strong>EC type:</strong>
		  <%= @ne.ectype %>
		</p>
		<p>
		  <strong>System:</strong>
		  <%= @ne.system %>
		</p>
      </div>
    </div> <!-- load-list -->
</div>