config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  
  resources :users do
    get '1830'
    get 'check_on_server', to: 'users#check_on_server', as: :check_on_server

    resources :nes do#, only: [:new, :create, :destroy]
      post 'upgrade'
      get 'delete'
      get 'ping_result'
      get 'version_result'
    end

    resources :branches do
      get 'delete'
      get 'update'
      get 'update_result'
    end
  end

end

app/models/ne.rb
class Ne < ActiveRecord::Base
	belongs_to :user
	 
	validates :ip, :presence => true, :uniqueness => true,
  		:format => { :with => Resolv::IPv4::Regex }

  	validates :name, presence: true, :uniqueness => true
  	validates :system, presence: true
  	validates :branch_name, presence: true
  	validates :ectype, presence: true

  	JOB_STATUS = { :done => "done", :start => "in-progress"}
end

app/controllers/nes_controller.rb
class NesController < ApplicationController
  before_action :set_user
  before_action :set_ne  #, only: [:show, :edit, :update, :destroy]

	# =================================================================
  def index
  end

  def ping_result
    #needs an actual refresh
    @ne = @user.nes.find(@ne[:id])
    if @ne[:isonline]
      wording = "Online"
    else
      wording = "Out of reach"
    end
    data = {:id => @ne[:id], :ne_status => wording}
    #data = {:id => @ne[:id], :status => time}
    render json: data, status: :ok
  end

  #issue version update to run in background
  def version
    time =  (Time.now - @ne[:updated_at]).seconds / 60 # minutes
    if time > 15
      PingerJob.perform_async(@user, @ne)
    end
    # else old value is left
    render :nothing
  end

  def version_result
    if @ne[:isonline]
      wording = "Online"
    else
      wording = "Out of reach"
    end
    data = {:id => @ne[:id], :status => wording}
    #data = {:id => @ne[:id], :status => time}
    render json: data
  end

  # GET /nes/new
  def new
  	@ne = @user.nes.new
  end
  # POST /nes
  def create
    @ne = @user.nes.new(ne_params)
    @ne.branch_id = getBranchByName(@ne.branch_name).id
    @ne.job_status = Ne::JOB_STATUS[:start]

    @ne.save
    respond_to do |format|
      format.js {flash[:notice] = "NE was created"}
      #params = {user: @user,  ne: @ne }
      #redirect_to your_controller_action_url and return
      #add_job('ping', params)
    end
  end

  # GET /nes/edit
  def edit
  end

  def delete
    #@branch = @user.branches.find(params[:branch_id])
  end
  
  # PATCH/PUT /nes/1
  def update
    # Update NE record with branch_id reference
    branch_id = getBranchByName(ne_params[:branch_name]).id
    branch_param = {}
    if branch_id != nil
      branch_param = {branch_id: branch_id}
    end

    respond_to do |format|
      format.js {flash[:notice] = "NE was updated"}
    end
    @ne.update_attributes(ne_params)
    @ne.update_attributes(branch_param)
  end

  # DELETE /nes/1
  # NOT JS
  def destroy
    @ne.destroy
    #respond_to do |format|
    #  format.js {flash[:notice] = "NE was deleted"}
    #end
    respond_to do |format|
      format.html { redirect_to root_path, notice: "NE was deleted" }
    end
  end

  #==================================================================================================================================================================================

	# =================================================================
	def getVersion (system)
	# =================================================================
		@dir = '/home/astariko/APT/aptDev/testcase/ot/encryption/KMT/'
		@command = 'cd ' +@dir + '; python ne_handshake.py --system ' 
							+system + ' --config ne_handshake.cfg'

		# clear file manually ...
		`#{@command}`

		# sort of run checks in background whether it was finished... << That is interesting.
		# OR! run tests on all systems at once.  Each one can write to system_name.txt
			
	end

	def upgrade
		notice = 'Upgrade request issued successfully'


		command =  "apt runstart ot_encrypt_upgrade_Testcase.py --system " + @ne['system'] + " --une " + @ne['name'] + " --uroot " + @user['rootecx'] + " --uload " + @user['uload'].to_s
		respond_to do |format|
			format.html { redirect_to root_path, notice: command }
		end
	end


  # =================================================================
  def getBranchByName(name)
  # =================================================================
    return @user.branches.find_by(name: name)
  end

  #==================================================================================================================================================================================
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.first
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_ne
      if params.include? :ne_id
        @ne = @user.nes.find(params[:ne_id])
      end
      if params.include? :id
      	@ne = @user.nes.find(params[:id])
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def ne_params
      params.require(:ne).permit(:name, :ip, :ectype, :system, :branch_name)
    end

end

app/views/nes/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete NE</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you wish to delete <b><%= @ne.name %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to "Confirm", user_ne_path(@user, @ne), method: :delete, class: "btn btn-primary" %>
    <%= link_to "Cancel", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/nes/_edit.html.erb
<div class="modal-dialog">
  <div class="modal-content">
	<div class="modal-header">
	  <h3><%= "Editing #{@ne.name}" %></h3>
	</div>
	<%= render "form" %>
  </div>
</div>

app/views/nes/_form.html.erb
<%= form_for [@user, @ne], remote: true, html: { style: "display:inline;" } do |f| %>

  <div class="modal-body">
    <ul class="errors"></ul>

    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :ip %><br>
      <%= f.text_field :ip %>
    </div>
    <div class="form-group">
      <%= f.label :system %><br>
      <%= f.text_field :system %>
    </div>
    
    <div class="form-group">
      <label for="ectype_name">Select EC type:</label>
      <br>
      <select  id="ectype_name" name="ne[ectype]">
      <!--                          NE list                              -->
      <% for ectype in @user.ectypes %>
        <% if @ne.ectype != ectype %>     
          <option><%=ectype%></option>
        <% else %>
          <option selected><%=ectype%></option>
        <% end %>
      <% end %>
      </select>
    </div>

    <div class="form-group">
      <label for="branch_name">Select branch:</label>
      <br>
      <select  id="branch_name" name="ne[branch_name]">
      <!--                          NE list                              -->
      <% for branch in @user.branches %>
        <% if @ne.branch_name != branch.name %>     
          <option><%=branch.name%></option>
        <% else %>
          <option selected><%=branch.name%></option>
        <% end %>
      <% end %>
      </select>
    </div>

    <div class="modal-footer">
      <%= f.submit class: "btn btn-primary" %>
      <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
    </div>
  </div>
  
<% end %>

app/views/nes/_new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
	<div class="modal-header">
	<h3>New NE</h3>
	</div>
	<%= render "form" %>
  </div>
</div>

app/views/nes/_save.js.erb
$("ul.errors").html("")
<% if @ne.errors.any? %>
	
  <% @ne.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  location.reload();
<% end %>

app/views/nes/create.js.erb
<%= render "save" %>

app/views/nes/delete.js.erb
<!-- window.alert("hey") -->
$("#ne-modal").html("<%= j render 'delete' %>")
$("#ne-modal").modal("show")

app/views/nes/destroy.js.erb
location.reload();

app/views/nes/edit.js.erb
$("#ne-modal").html("<%= j render 'edit' %>")

<!-- Press F12, Console Press JS and Logging -->
<!-- console.log($("#branch-name")); -->

$("#ne-modal").modal("show")

app/views/nes/new.js.erb
$("#ne-modal").html("<%= j render 'new' %>")
$("#ne-modal").modal("show")

app/views/nes/update.js.erb
<%= render "save" %>